### ISSUE TITLE
bot.rbに未宣言の変数があって動作しない？

### ISSUE THREAD

**Issue by kirk3110** [hakuho01/AeonBot#28]
https://github.com/hakuho01/AeonBot/blob/316440f3b4813691f7a3a862d5a719fea29aac57/bot.rb#L34-L37
2箇所で`str.concat`してるけど、strっていう変数がないから動いてない気がします。

動かしてみるとこういうエラーが出ちゃいました。（今サーバで動いてるのはどうしてだろう？）
```
[ERROR : et-1 @ 2022-01-18 19:42:11.332] Exception: #<NameError: undefined local variable or method `str' for main:Object>
[ERROR : et-1 @ 2022-01-18 19:42:11.332] bot.rb:37:in `block in <main>'
```

通常メンションと同様に単に下記のようにするか、
```rb
event.respond "<@!#{event.user.id}>" + 'おはよう。'
```
concatを使うならこうかな？
でもあまりこういう書き方をするメリットはないような気がしますが、何か意図がありますか？
```rb
event.respond "<@!#{event.user.id}>".concat(`おはよう。')
```

**Comment by hakuho01** [comment]
修正済み
