### ISSUE TITLE
FPSチャンネルの人に時報を飛ばしたい

### ISSUE THREAD

**Issue by hakuho01** [hakuho01/AeonBot#31]
弱者さんからの要望

> 少し申し訳ないのですが、機能追加の要望をさせていただいてもよろしいでしょうか
> 現在、朝方までfpsチャンネルで通話した結果生活が破壊される事例が多発しているように思われます
> なので、特定の時間にfpsチャンネルにいる人間にリマインダーを飛ばす機能を実装してはいただけないかと
> rubyに関しては全くの無知かつ既に似たようなbotが無いか見てみたところ通話時間を追跡してくれるbotはあるものの、その通話内にいる人間にリマインダーを送るようなものは無いようなので……
> 本当にお手隙のときに実装するか、無理ならば無理で良いので……

**Comment by hakuho01** [comment]
要件定義
特定の時間(2:00から30分ごとに5時までとか？)にfpsチャンネルのメンバーを取得
メンバーのidを取得して"<@:〜> <@:〜> もう寝なさい"をfpsテキストに投下

やること
定期実行→wheneverというgemでcronの処理をできる
memberの#voice_channelメソッドでそのメンバーが入っているボイスチャンネルを返してくれるのでメンバー総ざらいしてfpsチャンネルに入っている人だけ……というのは一応可能だけどアホなので上の定義のような動きがしたい
特定のチャンネルに投下するのも確かあるはず

**Comment by hakuho01** [comment]
channel.usersで取得できる感じか？

**Comment by kirk3110** [comment]
一旦基本機能は実現済としてCloseします
