### ISSUE TITLE
リマインダー機能の追加

### ISSUE THREAD

**Issue by hakuho01** [hakuho01/AeonBot#6]
リマインダーチャンネルが現行死んでる(ほんとうの意味でチラシの裏になってる)ので、リマインダーの内容を、実際にリマインドしてくれるようにしたい。

機能要件
- DBないしそれに準ずる外部サービスを使って入力された予定を保存する
- そこから予定を呼び出して、チャンネルにメンション付きで投稿する

課題
- DBがダルい。DB触るならrailsでやりたい……(Googleカレンダーやスプレッドシートなどを利用する？)
- herokuの再起動タイミングが不明
- 予定を呼び出すのに毎分毎にクロールしなければならないのであればGoogleカレンダーなどのAPIのrate_limitを叩く可能性がある

**Comment by kirk3110** [comment]
そんなに膨大なデータにならないのであれば、予定データはオンメモリに持っておくのがいいかもしれませんね

アプリケーション起動時に、既に保存されている予定をDBから読み込む
↓
予定追加リクエストがあるたびにメモリ上のオブジェクトに追加＋DBにも予定を保存
↓
メモリ上のオブジェクトを毎分チェックして通知すべきものがあれば投稿

みたいな動きなら毎分DBを直接叩かなくてよさそう
DB保存に失敗した場合とかの例外処理とかがちょっとめんどくさい感じにはなりますが……

**Comment by kirk3110** [comment]
一旦基本機能は実現済としてCloseします
